### ISSUE TITLE
Karen Baque-- 

### ISSUE THREAD

**Issue by kbaque** [Theseus33/Nutrition-App#2]
I actually really enjoyed your project, I think it was really well thought out and the set up was clean as well. One suggestion that I have for this app would be for you to be able to keep track of your daily intakes like you mentioned before, But overall I thought it was pretty cool .

**Comment by Theseus33** [comment]
I totally agree and was planning on adding a calander function to better keep track of daily intake. Im looking to add more functionality to the project by adding both intake weight and maybe even a profile with age weight and height which could return the medical ideal weight for height to help set goals.
